[kora]
rate_limit = 1

[validation]
max_allowed_lamports = 1000000
max_signatures = 10
allowed_programs = [
    "11111111111111111111111111111111",  # System Program
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",  # Token Program
    "BomroFd4tDAGmSRcNCt7TZLkeaeH815KYzfCpSTjHSfP",
]
allowed_tokens = [
    "BomroFd4tDAGmSRcNCt7TZLkeaeH815KYzfCpSTjHSfP",  # test token
]
allowed_spl_paid_tokens = [
    "BomroFd4tDAGmSRcNCt7TZLkeaeH815KYzfCpSTjHSfP",  # test token
] 
disallowed_accounts = []